// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdwPwgmpVqQfoja0tnhwBXfix3v58fd3g',
    appId: '1:393013458412:web:531c977460f0db6bebbcc9',
    messagingSenderId: '393013458412',
    projectId: 'interview-99af8',
    authDomain: 'interview-99af8.firebaseapp.com',
    storageBucket: 'interview-99af8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCels-4ANfI8l26m4H1_v9YlFKZb_Ki3NY',
    appId: '1:393013458412:android:0c53f9688ca6b7a5ebbcc9',
    messagingSenderId: '393013458412',
    projectId: 'interview-99af8',
    storageBucket: 'interview-99af8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv4wcJ0jf8Hu9yxvwF-Kpth5EmuwK3wRI',
    appId: '1:393013458412:ios:b0daa83bbc7cbe75ebbcc9',
    messagingSenderId: '393013458412',
    projectId: 'interview-99af8',
    storageBucket: 'interview-99af8.appspot.com',
    iosBundleId: 'com.example.interview',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCv4wcJ0jf8Hu9yxvwF-Kpth5EmuwK3wRI',
    appId: '1:393013458412:ios:b0daa83bbc7cbe75ebbcc9',
    messagingSenderId: '393013458412',
    projectId: 'interview-99af8',
    storageBucket: 'interview-99af8.appspot.com',
    iosBundleId: 'com.example.interview',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdwPwgmpVqQfoja0tnhwBXfix3v58fd3g',
    appId: '1:393013458412:web:e08b7c61d3310381ebbcc9',
    messagingSenderId: '393013458412',
    projectId: 'interview-99af8',
    authDomain: 'interview-99af8.firebaseapp.com',
    storageBucket: 'interview-99af8.appspot.com',
  );
}
